# Generated by Django 2.2 on 2020-03-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[(1, 'Administrator'), (2, 'Regular User')], default=2, help_text='Account Type', max_length=6),
        ),
    ]
