# Generated by Django 2.2 on 2020-03-17 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_update_role_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='category',
        ),
    ]
