# Generated by Django 2.2 on 2020-03-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_myuser_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'User'},
        ),
    ]
