# Generated by Django 2.2 on 2020-03-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200319_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Administrator'), (2, 'Regular User')], default=2, help_text='Account Type', max_length=6),
        ),
    ]
